### ISSUE TITLE
Database download

### ISSUE THREAD

**Issue by antoiner77** [soruly/trace.moe-api#166]
Hi, thanks for this, the project is very cool. Is there by chance a download link possible for the solr cores somewhere ? (quite a task to create it from scratch, I bet it was not fun haha) I have seen an old torrent with an outdated one but no recent version.

Thanks :)

**Comment by soruly** [comment]
I'll release a dump every April and October. So you'll have to wait until October to get an updated version. https://nyaa.si/view/1510357

Meanwhile, I'm planning to allow users to download the pre-hashed .xml.xz files directly from trace.moe's server. But it takes time to develop the tools, and there're a lot of design details to work out.

**Comment by antoiner77** [comment]
Oh nice! Thanks for the link it's actually perfect :)
