### ISSUE TITLE
sqlite return SqliteError: select `id` from `file` where `path` ilike '1/temp.mkv' limit 1 - near "ilike": syntax error

### ISSUE THREAD

**Issue by Leonhardt92** [soruly/trace.moe-api#362]
https://github.com/soruly/trace.moe-api/blob/35ab78319c240953a31b039ad3767cd0abd2495f/src/video.js#L79

![image](https://github.com/user-attachments/assets/27051563-f472-455f-a3a5-4d4ac4145f6a)

**Comment by soruly** [comment]
Fixed in b42ffe7
Thanks for reporting ;)
