### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ShinNouzen** [soruly/trace.moe-api#64]
Can you please make a wraper for it with the method of buffer?

**Comment by soruly** [comment]
What programming language do you want?

**Comment by ShinNouzen** [comment]
Javascript or Typescript

**Comment by soruly** [comment]
I think the HTTP API is simple enough so I don't want to wrap it again to make things more complex.

Instead, I'd suggest you make your own library like:

```javascript
export default async (imagePath) => fetch("https://api.trace.moe/search", {
  method: "POST",
  body: fs.readFileSync(imagePath),
  headers: { "Content-type": "image/jpeg" },
}).then((e) => e.json());
```

And then you use the wrapper library like:
```
import trace from "./lib/trace-moe.js";
console.log(await trace("foo-bar.jpg"));
```

**Comment by ShinNouzen** [comment]
> I think the HTTP API is simple enough so I don't want to wrap it again to make things more complex.
> 
> Instead, I'd suggest you make your own library like:
> 
> ```js
> export default async (imagePath) => fetch("https://api.trace.moe/search", {
>   method: "POST",
>   body: fs.readFileSync(imagePath),
>   headers: { "Content-type": "image/jpeg" },
> }).then((e) => e.json());
> ```
> 
> And then you use the wrapper library like:
> 
> ```
> import trace from "./lib/trace-moe.js";
> console.log(await trace("foo-bar.jpg"));
> ```
I just found a lib for the api. But anyways, thanks for looking at my issue.
